apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflection
  labels:
    app: reflection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reflection
  template:
    metadata:
      labels:
        app: reflection
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          value: "spot"
          operator: "Equal"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: agentpool
                  operator: NotIn
                  values:
                  - default 
      containers:
      - name: reflection
        image: carlosflor25/reflection:v1 
        env:
        - name: HTTP_CODE 
          value: "200"
        - name: METADATA_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: METADATA_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
      
