apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-ttmtools-lowers-eastus2-01
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://ttmtoolslowerseastus201-lnbvbj2n.hcp.eastus2.azmk8s.io
  project: platform-tools
  source:
    repoURL: https://github.com/carlosgit2016/service-mesh-comparison-poc.git  
    targetRevision: HEAD 
    path: "3-addons/"
    directory:
      recurse: false 
      jsonnet: {}
      include: 'prometheus.yaml'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
